AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Description: Environment name
    Default: dev


Resources:
  UserPool:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
          GetResource:
          Type: Api
          Properties:
              Path: /{proxy+}
              Method: get
