AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  djeurnie-core
  
  Sample SAM Template for djeurnie-core

Resources:
  DjeurnieDefaultIdp:
    Type: AWS::Serverless::Application
    Properties:
      Location: idp.yaml
      Parameters:
        CognitoUserPoolName: djeurnie-default
        CognitoUserPoolClientName: djeurnie-web-client
