AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  djeurnie-core
  
  Sample SAM Template for djeurnie-core

Parameters:
  Environment:
    Type: String
    Description: Environment name
    Default: dev

Resources:
  DjeurnieDefaultIdp:
    Type: AWS::Serverless::Application
    Properties:
      Location: idp.yaml
      Parameters:
        CognitoUserPoolName: djeurnie-default
        CognitoUserPoolClientName: djeurnie-web-client
  OrderApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: order.yaml
      Parameters:
        Environment: !Ref Environment
