AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  egress magic

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  EgressHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration: true
  EgressFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: egress
      Runtime: go1.x
      CodeUri: egress/
      Policies:
        - AmazonDynamoDBFullAccess
      Architectures:
        - x86_64
      Events:
        GetEgress:
          Type: HttpApi
          Properties:
            ApiId: !Ref EgressHttpApi
            Path: /{tenant}/egress/{model}/{id}
            Method: GET
            PayloadFormatVersion: "2.0"
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
          - ''
          - - ApplicationInsights-SAM-
            - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
          - ''
          - - ApplicationInsights-SAM-
            - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup

Outputs:
  HttpApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${EgressHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'
